trigger: none
pr: none
# I've disabled CI and PR triggers on the fetcher pipe to avoid commit deployments.  

resources:
  pipelines:
    - pipeline: source
      project: PipeFromPipe
      source: source
      trigger: 
        branches:
          include:
          - master
steps:
  - checkout: none
  - script: echo 'triggered fetcher'